### ISSUE TITLE
Auto update fail at 1.2.0

### ISSUE THREAD

**Issue by Chlna6666** [superx101/CALL#10]
![Screenshot_2023-07-31-08-28-04-62_2665fb67b16260a8d818298cef8dc107.jpg](https://github.com/superx101/CALL/assets/79357769/6ce5cd6a-2548-4452-a41e-ad91ac4d0e51)

通过https://c.runoob.com/front-end/51/
解压app.js
就不会有问题
![Screenshot_2023-07-31-08-53-02-72_2665fb67b16260a8d818298cef8dc107.jpg](https://github.com/superx101/CALL/assets/79357769/0700af35-d156-4cbd-9f01-3fc88251be35)

**Comment by superx101** [comment]
感谢反馈
应该不是压缩和解压的问题，1.2.0新增了个配置项consoleLanguage，自动更新时[JsonPatch](https://github.com/superx101/CALL/blob/main/src/util/JsonPatch.ts)没有成功的把该项添加上，导致没有通过配置文件检测而报错。

**Comment by Chlna6666** [comment]
> 感谢反馈
> 应该不是压缩和解压的问题，1.2.0新增了个配置项consoleLanguage，自动更新时[JsonPatch](https://github.com/superx101/CALL/blob/main/src/util/JsonPatch.ts)没有成功的把该项添加上，导致没有通过配置文件检测而报错。

本来是想解压下来看一看到底是哪一个问题 结果解压就好了

**Comment by superx101** [comment]
Fixed in: 6ebf70997d0f4d43f3f7496143dca175ca056cc7
